import React from "react";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { theme } from '@/lib/theme';
import Structure from '@/components/Structure/Structure';
import '@mantine/core/styles.css';
import { getLoggedInUser } from "@/lib/actions/user.actions";
import { redirect } from "next/navigation";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getLoggedInUser();
  if (user) {
    redirect("/book");
  }
  return (
    <html lang="en">
    <head>
      <ColorSchemeScript />
    </head>
    <body>
    <MantineProvider theme={theme} defaultColorScheme="dark">
      {children}
    </MantineProvider>
    </body>
    </html>
  );
}
